# Generated by Django 3.0.5 on 2020-04-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0027_auto_20200427_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='state',
            new_name='mxlr_handle',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='on_downtown_craft_beer_trail',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='tap_list_provider',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='twitter_short_location_description',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='untappd_url',
        ),
        migrations.AddField(
            model_name='venue',
            name='spreaker_channel',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='venue',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.DeleteModel(
            name='VenueAPIConfiguration',
        ),
    ]
