# Generated by Django 3.0.6 on 2020-05-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0028_auto_20200429_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='time_zone',
        ),
    ]
