# Generated by Django 3.0.4 on 2020-04-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='speaker',
        ),
        migrations.AddField(
            model_name='event',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='qa_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
