# Generated by Django 3.0.4 on 2020-04-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200428_1450'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_venue_i_a66338_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_venue_i_4e58c8_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='stream_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
