# Generated by Django 3.0.5 on 2020-04-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200428_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly')], default='Once', max_length=10),
        ),
    ]
