# Generated by Django 3.0.5 on 2020-05-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0028_auto_20200429_1601'),
        ('events', '0007_auto_20200429_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venues.Venue'),
        ),
    ]
