# Generated by Django 3.0.6 on 2020-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200504_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='GMT', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='stream_link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='stream_medium',
            field=models.CharField(max_length=50),
        ),
    ]
