# Generated by Django 3.0.6 on 2020-05-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200506_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stream_link',
            field=models.URLField(null=True),
        ),
    ]
